// products.js
import { productImages } from "./assets";

export const products = [
    {
        id: 1,
        name: "Premium Headphones",
        price: 999,
        category: "Electronics",
        qty: 10,
        image: productImages.p1,
    },
    {
        id: 2,
        name: "Smart Watch",
        price: 1299,
        category: "Electronics",
        qty: 5,
        image: productImages.p2,
    },
    {
        id: 3,
        name: "Wireless Earbuds",
        price: 799,
        category: "Accessories",
        qty: 12,
        image: productImages.p3,
    },
    {
        id: 4,
        name: "Casual Shirt",
        price: 1599,
        category: "Fashion",
        qty: 8,
        image: productImages.p4,
    },
    {
        id: 5,
        name: "Stylish Jacket",
        price: 1999,
        category: "Fashion",
        qty: 3,
        image: productImages.p5,
    },
    {
        id: 6,
        name: "Phone Stand",
        price: 499,
        category: "Accessories",
        qty: 20,
        image: productImages.p6,
    },
    {
        id: 7,
        name: "Home Decor Lamp",
        price: 899,
        category: "Home",
        qty: 7,
        image: productImages.p7,
    },
    {
        id: 8,
        name: "Table Organizer",
        price: 1099,
        category: "Home",
        qty: 6,
        image: productImages.p8,
    },
    {
        id: 9,
        name: "Gaming Mouse",
        price: 1399,
        category: "Electronics",
        qty: 9,
        image: productImages.p9,
    },
    {
        id: 10,
        name: "Backpack",
        price: 699,
        category: "Accessories",
        qty: 15,
        image: productImages.p10,
    },
];